# Generated by Django 3.2.6 on 2021-08-23 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=60)),
                ('bio', models.CharField(max_length=240)),
                ('email', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='description',
            field=models.CharField(default='foo', max_length=240),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='creator',
            field=models.ForeignKey(default='foo', on_delete=django.db.models.deletion.CASCADE, to='tutorapi.user'),
            preserve_default=False,
        ),
    ]
