import { useState, useEffect } from "react";
import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  const [user, setUser] = useState(null);

  useEffect(() => {
    setUser(localStorage.getItem('user'));
  }, [])


  const nonLoggedIn = (
    <>
      <h2>
        Welcome to tutor site!
      </h2>
      <p>
        <Link href="/login"><a>Login </a></Link>
        or
        <Link href="/create_account"><a> create an account </a></Link>
        to get started.
      </p>
    </>
  )

  const loggedIn = (
    <>
      <h2>
        Welcome back to tutor site, {user}!
      </h2>
      <p>
        You can check out the tutor reqests 
        <Link href="/tutor_requests"><a> here</a></Link>
        !
      </p>
    </>
  )

  return (
    <div>
      <Head>
        <title>Tutor Site</title>
        <meta name="description" content="Originally generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {user ? loggedIn : nonLoggedIn}
    </div>
  )
}
